# Generated by Django 2.1.3 on 2019-01-18 17:10

import backend.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('birthday', models.DateTimeField(blank=True, verbose_name='Birthday')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=backend.user.models.source_image_file)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('user_cv', models.FileField(blank=True, null=True, upload_to=backend.user.models.source_cv_file)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
